middlewares:
  REQUEST_CREATED:
    type: REQUEST_CREATED
    middlewares:
      # - TestApp\CustomMiddleware
      # - TestApp\AnotherCustomMiddleware

  CONTROLLER_MATCHED:
    type: CONTROLLER_MATCHED
    middlewares:
      - TestApp\CustomMiddleware
